{"name": "Test to verify get user by Invalid Auth Token", "status": "failed", "statusDetails": {"message": "AssertionError: Status code is wrong\nassert 200 == 401\n +  where 200 = <Response [200]>.status_code", "trace": "self = <functional_api_test.test_get_user_details_all.TestGetUser object at 0x10be45850>\n\n    @mark.getUser\n    @mark.user\n    @allure.title(\"Test to verify get user by Invalid Auth Token\")\n    def test_get_user_details_invalid_auth(self):\n        GET_USER_URL = ApiUrls.GET_USER\n        print(\"URL --> \", GET_USER_URL)\n        header = CommonUtility.get_custom_header()\n        header['Authorization'] = \"wrong\"\n        response = FrameworkUtils.fire_api_with_custom_headers(\"GET\",\n                                                               request_url=GET_USER_URL,\n                                                               headers=header)\n        print(response.json())\n>       assert response.status_code == 401, \"Status code is wrong\"\nE       AssertionError: Status code is wrong\nE       assert 200 == 401\nE        +  where 200 = <Response [200]>.status_code\n\nfunctional_api_test/test_get_user_details_all.py:38: AssertionError"}, "start": 1698438057917, "stop": 1698438058060, "uuid": "be72a0dd-f3ad-44b0-ae38-327b0d6d5793", "historyId": "fa13f3b2423d44e243bb777c53acaba5", "testCaseId": "fa13f3b2423d44e243bb777c53acaba5", "fullName": "functional_api_test.test_get_user_details_all.TestGetUser#test_get_user_details_invalid_auth", "labels": [{"name": "suite", "value": "User Service API"}, {"name": "tag", "value": "user"}, {"name": "tag", "value": "getUser"}, {"name": "parentSuite", "value": "functional_api_test"}, {"name": "subSuite", "value": "TestGetUser"}, {"name": "host", "value": "BBMDVPAYZAPP"}, {"name": "thread", "value": "83572-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "functional_api_test.test_get_user_details_all"}]}